export const Products = [
  {
    id: '01',
    name: "Syltherine",
    current_price: 2500000,
    original_price: 3500000,
    Discount: 30,
    new_product: true,
    product_type: "Stylish cafe chair",
    quantity: 1,
    image: "assets/images/Product_Image/productimg1.png",
    Category: "Furniture",
  },
  {
    id: '02',
    name: "Leviosa",
    current_price: 1500000,
    original_price: 2000000,
    Discount: 25,
    new_product: false,
    product_type: "Luxury dining chair",
    quantity: 1,
    image: "assets/images/Product_Image/productimg2.png",
    Category: "Furniture",
  },
  {
    id: '03',
    name: "Lolito",
    current_price: 1200000,
    original_price: 1700000,
    Discount: 29,
    new_product: true,
    product_type: "Ergonomic office chair",
    quantity: 2,
    image: "assets/images/Product_Image/productimg3.png",
    Category: "Office Supplies",
  },
  {
    id: '04',
    name: "Respira",
    current_price: 950000,
    original_price: 1250000,
    Discount: 24,
    new_product: false,
    product_type: "Modern minimalist chair",
    quantity: 1,
    image: "assets/images/Product_Image/productimg4.png",
    Category: "Home Decor",
  },
  {
    id: '05',
    name: "Grifo",
    current_price: 500000,
    original_price: 750000,
    Discount: 33,
    new_product: true,
    product_type: "Foldable picnic chair",
    quantity: 3,
    image: "assets/images/Product_Image/productimg5.png",
    Category: "Outdoor",
  },
  {
    id: '06',
    name: "Muggo",
    current_price: 450000,
    original_price: 600000,
    Discount: 25,
    new_product: false,
    product_type: "Classic wooden chair",
    quantity: 5,
    image: "assets/images/Product_Image/productimg6.png",
    Category: "Furniture",
  },
  {
    id: '07',
    name: "Pingky",
    current_price: 200000,
    original_price: 300000,
    Discount: 33,
    new_product: true,
    product_type: "Children's high chair",
    quantity: 1,
    image: "assets/images/Product_Image/productimg4.png",
    Category: "Kids",
  },
  {
    id: '08',
    name: "Circulo",
    current_price: 700000,
    original_price: 850000,
    Discount: 18,
    new_product: false,
    product_type: "Swivel gaming chair",
    quantity: 1,
    image: "assets/images/Product_Image/productimg5.png",
    Category: "Gaming",
  },
  {
    id: '09',
    name: "Bendito",
    current_price: 1300000,
    original_price: 1750000,
    Discount: 26,
    new_product: true,
    product_type: "Reclining armchair",
    quantity: 7,
    image: "assets/images/Product_Image/productimg1.png",
    Category: "Home Comfort",
  },
  {
    id: '10',
    name: "Optima",
    current_price: 800000,
    original_price: 1000000,
    Discount: 20,
    new_product: false,
    product_type: "Outdoor patio chair",
    quantity: 2,
    image: "assets/images/Product_Image/productimg2.png",
    Category: "Outdoor",
  },
];
